#!/usr/bin/env bash

declare -r git_tag="$(git describe --tags --abbrev=0)"
declare -r head_count=$(git rev-list --count HEAD)
declare -r tag_count=$(git rev-list --count "${git_tag:?}")
declare -r count_diff=$((${head_count:?} - ${tag_count:?}))
declare image_tag="${git_tag:?}"

[[ ${count_diff} -gt 0 ]] && image_tag+="-dev.${count_diff:?}"
[[ -n $(git status -s) ]] && image_tag+="-dirty"

echo "building tag ${image_tag:?}"
docker buildx build --platform linux/amd64,linux/arm64 -t "kristofferahl/baseops:${image_tag:?}" "$@" . --push
